# Generated by Django 6.0.3 on 2026-04-02 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(choices=[('urgences', 'Urgences'), ('cardiologie', 'Cardiologie'), ('chirurgie', 'Chirurgie'), ('pediatrie', 'Pédiatrie'), ('neurologie', 'Neurologie'), ('orthopédie', 'Orthopédie'), ('gynécologie', 'Gynécologie'), ('réanimation', 'Réanimation'), ('oncologie', 'Oncologie'), ('pneumologie', 'Pneumologie'), ('gastroentérologie', 'Gastroentérologie'), ('dermatologie', 'Dermatologie')], max_length=50)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('stable', 'Stable'), ('critical', 'Critical'), ('maintenance', 'Maintenance')], default='empty', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department', 'room_number'],
            },
        ),
    ]
