# Generated by Django 6.0.3 on 2026-04-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
