# ============================================================
# patients/models.py
# This file defines what a Patient looks like in the database
# A patient record is created by the doctor first
# Then the patient registers using a one-time code
# ============================================================

from django.db import models
from users.models import User
from doctors.models import Doctor  # Patient is assigned to a Doctor


class Patient(models.Model):

    # ── STATUS CHOICES ───────────────────────────────────────
    # These are the only allowed values for the status field
    STATUS_CHOICES = [
        ('stable',   'Stable'),
        ('alert',    'Alert'),
        ('critical', 'Critical'),
    ]

    # ── LINK TO USER ACCOUNT ─────────────────────────────────
    # null=True, blank=True means this can be empty
    # Why? Because the doctor creates the patient record FIRST
    # The patient account is linked LATER when they register
    # with the one-time code
    user = models.OneToOneField(
        User,
        on_delete=models.SET_NULL,  # if user deleted, keep patient record
        null=True,
        blank=True,
        related_name='patient_profile'
    )

    # ── LINK TO PRIMARY DOCTOR ───────────────────────────────
    # Every patient is assigned to one primary doctor
    # on_delete=SET_NULL means if doctor deleted, keep patient record
    primary_doctor = models.ForeignKey(
        Doctor,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='patients'  # doctor.patients.all() gives all their patients
    )

    # ── PATIENT INFORMATION ──────────────────────────────────
    full_name    = models.CharField(max_length=200)
    patient_code = models.CharField(max_length=20, unique=True)  # e.g. P001234
    dob          = models.DateField()                             # date of birth
    blood_type   = models.CharField(max_length=5, blank=True)    # e.g. O+, A-
    phone        = models.CharField(max_length=20, blank=True)
    insurance_id = models.CharField(max_length=50, blank=True)

    # Current health status — default is stable
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='stable'
    )

    # ── ONE-TIME REGISTRATION CODE ───────────────────────────
    # Generated by the doctor when patient comes for first visit
    # Patient uses this code to register on the app
    reg_code        = models.CharField(max_length=10, blank=True, null=True)
    code_expires_at = models.DateTimeField(blank=True, null=True) # valid 48h
    code_used       = models.BooleanField(default=False)          # used or not

    # ── TIMESTAMPS ───────────────────────────────────────────
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)  # updates every time record changes

    def __str__(self):
        return f"{self.full_name} ({self.patient_code})"


# ============================================================
# MEDICAL DOSSIER MODEL
# Each patient has a PDF medical dossier stored in MinIO
# Every time doctor uploads a new PDF → new version is created
# Old versions are kept for history
# ============================================================
class MedicalDossier(models.Model):

    # Which patient this dossier belongs to
    patient = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
        related_name='dossiers'  # patient.dossiers.all() gives all versions
    )

    # Which doctor uploaded this version
    doctor = models.ForeignKey(
        Doctor,
        on_delete=models.SET_NULL,
        null=True,
        related_name='uploaded_dossiers'
    )

    # Path to the PDF file in MinIO storage
    # e.g. "patients-dossiers/P001234/v3.pdf"
    pdf_url = models.CharField(max_length=500)

    # Version number — auto incremented each time doctor uploads new PDF
    version = models.IntegerField(default=1)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Dossier v{self.version} — {self.patient.full_name}"